import Footer from "@/Components/footer";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Landrup dans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
